spring.application.name=api-gateway
server.port=8080
grpc.client.order-service.address=static://localhost:9091
grpc.client.order-service.negotiationType=PLAINTEXT
management.endpoints.web.exposure.include=health,info
