spring.application.name=order-service
server.port=8081
grpc.server.port=9091
grpc.client.pricing-service.address=static://localhost:9092
grpc.client.pricing-service.negotiationType=PLAINTEXT
grpc.client.inventory-service.address=static://localhost:9093
grpc.client.inventory-service.negotiationType=PLAINTEXT
grpc.client.analytics-service.address=static://localhost:9094
grpc.client.analytics-service.negotiationType=PLAINTEXT
management.endpoints.web.exposure.include=health,info
